In [26]:
import numpy as np
arr=np.array([2,3,34,7,57,7],dtype=np.int64)
arr

array([ 2,  3, 34,  7, 57,  7])

In [18]:
print(arr.size)
print(type(arr))
print(arr.shape)
print(arr.itemsize)
print(arr.ndim)

7
<class 'numpy.ndarray'>
(7,)
2
1


In [19]:
np.arange(1,20,5)

array([ 1,  6, 11, 16])

In [20]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [21]:
arr.itemsize

2

In [37]:
arr.reshape(3,2)

array([[ 2,  3],
       [34,  7],
       [57,  7]])

In [40]:
np.zeros((5,2),dtype=bool)

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [39]:
np.ones(8,dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [44]:
np.random.rand(10)*100

array([18.10014453, 38.04989261, 94.08560972, 18.54471094, 67.33481048,
        0.74255306,  2.20156249,  2.95399913, 28.83249485, 76.13936229])

In [55]:
arr2=np.array((2,34,3,5,646,6))
arr2

array([  2,  34,   3,   5, 646,   6])

In [54]:
arr2[3:-2:-1]

array([], dtype=int64)

In [57]:
arr2[arr2<10]

array([2, 3, 5, 6])

In [59]:
arr3 = np.array([1, 2, 3, 4, 5])
print(arr3 + 10)   # [11 12 13 14 15] - Addition
print(arr3 - 2)    # [-1  0  1  2  3] - Subtraction
print(arr3 * 2)    # [ 2  4  6  8 10] - Multiplication
print(arr3 / 2)    # [0.5 1.  1.5 2.  2.5] - Division
print(arr3 // 2)   # [0 1 1 2 2] - Floor Division
print(arr3 % 2)    # [1 0 1 0 1] -remainder


[11 12 13 14 15]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[0 1 1 2 2]
[1 0 1 0 1]
